_1 #---ENSEMBLER COMMAND SCRIPT GENERATED BY CCP4I---

1 input
1 \\173
LOOP N 1 $NPDBINS
1     model = $PDBIN($N)
ENDLOOP
LOOP N 1 $NALIGNMENTS
1     alignment = $ALNIN($N)
ENDLOOP
1 \\175

1 output
1 \\173
1     location = $OUTPUT_FOLDER
1     root = $OUTPUT_ROOT
1     style = $OUTPUT_STYLE
1     sort = $OUTPUT_SORT
1 \\175

1 configuration
1 \\173
1     superposition
1     \\173
1         method = $CONFIG_SUPERPOSITION_METHOD
1         convergence = $CONFIG_SUPERPOSITION_CONVERGENCE
1     \\175
 
1     mapping = $CONFIG_MAPPING
1     atoms = $CONFIG_ATOMS
1     clustering = $CONFIG_CLUSTERING
 
1     weighting
1     \\173
1         scheme = $CONFIG_WEIGHTING_SCHEME
1         convergence = $CONFIG_WEIGHTING_CONVERGENCE
1         incremental_damping_factor = $CONFIG_WEIGHTING_DAMPING_INCR
1         max_damping_factor = $CONFIG_WEIGHTING_DAMPING_MAX
 
1         robust_resistance
1         \\173
1             critical = $CONFIG_WEIGHTING_RR_CRITICAL
1         \\175
1     \\175
 
1     trim = $CONFIG_TRIM
 
1     trimming
1     \\173
1         threshold = $CONFIG_TRIMMING_THRESHOLD
1     \\175
1 \\175

