#
#     Copyright (C) 1999-2004  Liz Potterton, Peter Briggs
#
#     This code is distributed under the terms and conditions of the
#     CCP4 Program Suite Licence Agreement as a CCP4 Library.
#     A copy of the CCP4 licence can be obtained by writing to the
#     CCP4 Secretary, Daresbury Laboratory, Warrington WA4 4AD, UK.
#
#CCP4i_cvs_Id $Id$
#======================================================================
#
# edit_dname script
#
#======================================================================

  CreateComScript  edit_dname cad_script
  set cmd "[BinPath cad] HKLIN1 \"$HKLIN\" HKLOUT \"$HKLOUT\""

  set status [Execute $cmd $cad_script program_status report ]
