#
#     Copyright (C) 1999-2004  Liz Potterton, Peter Briggs
#
#     This code is distributed under the terms and conditions of the
#     CCP4 Program Suite Licence Agreement as a CCP4 Library.
#     A copy of the CCP4 licence can be obtained by writing to the
#     CCP4 Secretary, Daresbury Laboratory, Warrington WA4 4AD, UK.
#
#======================================================================
#
# pdb2to3 script
#
#======================================================================

  CreateComScript pdb2to3 pdb2to3_script

  set cmd "[BinPath pdb2to3] -f [FileJoin [FileJoin [GetEnvPath CCP4] share] ccp4srs] \"$XYZIN\" \"$XYZOUT\" "

  set status [Execute $cmd $pdb2to3_script program_status report ]

