#===========================================================================
#
# phaser_MR.script
#
#===========================================================================
 
  set OUTPUT_FILE_ROOT "[SetOutputFileRoot]"

  CreateComScript phaser_MR phaser_MR_script -ampersand

  set cmd "[BinPath phaser]"

  set status [Execute $cmd $phaser_MR_script program_status report]

  set phaserfiles [glob "[SetOutputFileRoot].*"]

  foreach file $phaserfiles { AddOutputFile $file "PROJECT" }
