#===========================================================================
#
# phaser_CCA.script
#
#===========================================================================
 
  set OUTPUT_FILE_ROOT "[SetOutputFileRoot]"

  CreateComScript phaser_CCA phaser_CCA_script -ampersand

  set cmd "[BinPath phaser]"

  set status [Execute $cmd $phaser_CCA_script program_status report]

  set SUM_FILE "[SetOutputFileRoot].sum"
  if { [file exists $SUM_FILE] } { AddOutputFile $SUM_FILE PROJECT }


