
   global env

   CreateComScript zanuda zanuda_script

   set cmd "[BinPath ccp4-python] -u [file join $env(CCP4) bin zanuda]"

   append cmd " hklin $HKLIN xyzin $XYZIN tmpdir [GetTmpFileName] stdin"

   if { $MODE == "REFINE" } {
      append cmd " hklout $HKLOUT xyzout $XYZOUT"
   } elseif { $MODE == "SAVE" } {
      append cmd " sgdir $SGDIR"
   }

   set status [Execute $cmd $zanuda_script program_status report]

