#!/bin/sh
echo "${MOSFLM_ROOT}mosflm < $HOME/.mosflm/batch.scr &> $HOME/.mosflm/remote.log"
${MOSFLM_ROOT}mosflm < $HOME/.mosflm/batch.scr &> $HOME/.mosflm/remote.log
echo `date` >> $HOME/.mosflm/remote.log
