#! /bin/sh

# An example of running an RF with Es in two different resolution ranges.
# Parameters expository only.  (The model was used in an attempt on MR in the
# toxd determination and didn't yield a solution.)

# $Id$

set -e
set -a

DIR=$CCP4_SCR 
modelpdb=$CEXAM/unix/runnable/1aal.brk 
mtzdata=$CEXAM/toxd/toxd
FPin=FTOXD3
BMAX=90                         # in this SG
rmult=0.9

for rf_reso in "12 4.5" "15 3"; do
  tag=`echo toxd-$rf_reso- | tr " " -` # yields toxd-<lores>-<hires>-

  $CEXAM/unix/runnable/auto-amore
done
#
