#!/bin/sh

# Modified version of Mike Hartshorn's original shell script to
# start the astexviewer program as a stand-alone application

# In Java 1.2 or better, you could use java -classpath to specify the
# the OpenAstexViewer classpath _or_ -jar to specify the jar file.
# But neither of these work for 1.1 so use the following construct
# instead to set the classpath correctly within this shell
#
# Set CLASSPATH to include the OpenAstexViewer jar file
if test "CLASSPATH"; then
  CLASSPATH=${CBIN}/OpenAstexViewer.jar:${CLASSPATH} java astex.MoleculeViewer ${1+"$@"}
else
  CLASSPATH=${CBIN}/OpenAstexViewer.jar java astex.MoleculeViewer ${1+"$@"}
fi
