#!/usr/bin/awk -f
#
# ccp4keys (Kevin Cowtan)
#
# Useage: ccp4keys <logfile>
#
# Function: extract all keywords form a logfile and display
# them in a format which can be cut and pasted into a new
# command file.
#
/^ Data line--- <a href=.*>........<\/a>/{sub("^ Data line--- ","");while(sub("<[^>]*>",""));print;}
/^ Data line--- /{sub("^ Data line--- ","");print;}

