#! /bin/sh -f

if test $# -gt 0 ; then
  if test "$1" = '-h' ; then
    echo "Usage: extractsummary < foo.log > foo.sum"
    exit
  fi
fi

# find awk executable
for myawk in nawk gawk awk ; do
  test -f $myawk && break
done

$myawk '/SUMMARY_BEGIN/,/SUMMARY_END/' | grep -v 'SUMMARY'


