#!/bin/sh

set -e

#  Read in coordinates to calculate structure factors. 
sfall		\
HKLIN $CEXAM/toxd/toxd.mtz \
HKLOUT $CCP4_SCR/toxd_sf.mtz \
XYZIN $CEXAM/toxd/toxd.pdb \
XYZOUT  $CCP4_SCR/junk.pdb \
<< END-sfall
TITLE Structure factors calculated for toxd.
GRID 152 96 64    !div CELL by these should give .=. 0.7 A
MODE SFCALC XYZIN HKLIN
RESOLUTION 37 2.1 
BINS  60
RSCB 8.0 2.1
FORMFACTOR Fe+3
LABIN FP=FTOXD3 SIGFP=SIGFTOXD3 -
      F0=FAU20 F1=SIGFAU20    -
      F2=FMM11 F3=SIGFMM11    -
      F4=FI100 F5=SIGFI100 FREE=FreeR_flag

LABOUT FC=FC_sf PHIC=AC_sf
END-sfall

#   Alternative to show it works 
#  Calculate map from atom coordinates
#  and then generate structure factors from map

sfall		\
XYZIN $CEXAM/toxd/toxd.pdb \
MAPOUT $CCP4_SCR/toxd_fc.map << END-sfall
TITLE Calculating "coordinate" map
GRID 152 96 64    !div CELL by these should give .=. 0.7 A
MODE ATMMAP
SYMMETRY 19
RESOLUTION 37 2.1 
BINS  60
RSCB 8.0 2.1
END-sfall

#  Read in map to calculate structure factors. 
sfall		\
HKLIN $CEXAM/toxd/toxd.mtz \
HKLOUT $CCP4_SCR/toxd_sf.mtz \
MAPIN $CCP4_SCR/toxd_fc.map << END-sfall
TITLE  calculating structure factors from "Fc" map
GRID 152 96 64    !div CELL by these should give .=. 0.7 A
MODE SFCALC MAPIN HKLIN
RESOLUTION 37 2.1 
BINS  60
RSCB 8.0 2.1
LABIN FP=FTOXD3 SIGFP=SIGFTOXD3  FREE=FreeR_flag
LABOUT FC=FC_sf PHIC=AC_sf
END-sfall
#
